spring:
  profiles:
    active: dev
    include: secret
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  sql:
#    init:
#      mode: always
#      continue-on-error: false
  servlet:
    multipart:
      enabled: true
  h2:
    console:
      enabled: false
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/**/*.xml
  type-aliases-package: com.kcc.pms.domain

cloud:
  aws:
    s3:
      bucket: kcc-bucket
      url: https://kcc-bucket.s3.ap-northeast-2.amazonaws.com/kcc_pms/
    credentials:
      access-key: ${cloud.aws.accessKey}
      secret-key: ${cloud.aws.secretKey}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

---
server:
  port: 8085
  servlet:
    session:
      timeout: 120m  # 120분으로 설정

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:oracle:thin:@${db.host}:${db.port}/xe
#    url: jdbc:log4jdbc:oracle:thin:@localhost:${db.port}:xe
    username: ${db.username}
    password: ${db.password}
    driver-class-name: oracle.jdbc.OracleDriver
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

API-SERVER:
  url: http://localhost:8085

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:oracle:thin:@${db.host}:${db.port}/xe
    #    url: jdbc:log4jdbc:oracle:thin:@localhost:${db.port}:xe
    username: ${db.username}
    password: ${db.password}
    driver-class-name: oracle.jdbc.OracleDriver
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

API-SERVER:
  url: http://13.125.32.253:8085